import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, WidthType, AlignmentType, BorderStyle,
  HeadingLevel, ShadingType, convertInchesToTwip,
} from 'docx';
import type { Enquiry } from './types';

const CO_NAME = 'Mangla Rubber Technologies';

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

// ── PDF ──────────────────────────────────────────────────────────────────────
export function downloadEnquiryPDF(enq: Enquiry) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const mx = 14, cw = 210 - mx * 2;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text(CO_NAME, mx, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('PURCHASE ENQUIRY', 210 - mx, 14, { align: 'right' });

  // Divider
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(mx, 17, 210 - mx, 17);

  // Meta grid
  let y = 22;
  const metaRows: [string, string][] = [
    ['Enquiry No.',   enq.id],
    ['Date Received', fmtDate(enq.recv)],
    ['Customer',      enq.cust],
    ['Contact',       enq.contact || '—'],
    ['Email',         enq.email || '—'],
    ['Source',        enq.src || '—'],
    ['Assigned To',   enq.assigned || '—'],
    ['Priority',      enq.urg || '—'],
  ];
  if (enq.custEnqDocNo) metaRows.splice(2, 0, ['Cust. Enq. No.', enq.custEnqDocNo]);

  const colW = cw / 2 - 2;
  metaRows.forEach(([label, value], i) => {
    const x = i % 2 === 0 ? mx : mx + colW + 4;
    if (i % 2 === 0 && i > 0) y += 6;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(120, 120, 120);
    doc.text(label.toUpperCase(), x, y);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(30, 30, 30);
    doc.text(value, x, y + 3.5);
  });
  y += 10;

  if (enq.notes) {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(120);
    doc.text('NOTES', mx, y);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(50);
    const lines = doc.splitTextToSize(enq.notes, cw);
    doc.text(lines, mx, y + 3.5);
    y += 3.5 + lines.length * 4.5 + 4;
  }

  // Items table
  autoTable(doc, {
    startY: y,
    head: [['#', 'Description', 'Material / Grade', 'Qty', 'UOM', 'Dwg Ref']],
    body: enq.items.map(i => [i.seq, i.desc, i.mat || '—', i.qty, i.uom || '—', i.drwg || '—']),
    theme: 'grid',
    headStyles: { fillColor: [220, 220, 220], textColor: [30, 30, 30], fontStyle: 'bold', fontSize: 8, cellPadding: 2 },
    bodyStyles: { fontSize: 8.5, cellPadding: 2, textColor: [40, 40, 40] },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      3: { cellWidth: 16, halign: 'center' },
      4: { cellWidth: 16, halign: 'center' },
      5: { cellWidth: 28 },
    },
    margin: { left: mx, right: mx },
  });

  y = (doc as any).lastAutoTable.finalY + 6;
  doc.setFont('helvetica', 'italic'); doc.setFontSize(7.5); doc.setTextColor(150);
  doc.text(`Generated by ${CO_NAME} ERP · ${new Date().toLocaleString('en-IN')}`, mx, y);

  doc.save(`${enq.id}.pdf`);
}

// ── DOCX ─────────────────────────────────────────────────────────────────────
export async function downloadEnquiryDOCX(enq: Enquiry) {
  const GRAY    = 'A0A0A0';
  const DARK    = '1E1E1E';
  const RED     = 'D42027';
  const HEADBG  = 'EEEEEE';

  const labelRun  = (t: string) => new TextRun({ text: t.toUpperCase(), size: 14, color: GRAY, bold: true, font: 'Calibri' });
  const valueRun  = (t: string) => new TextRun({ text: t, size: 18, color: DARK, font: 'Calibri' });
  const noBorder  = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
  const allNoBorder = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };

  function metaCell(label: string, value: string) {
    return new TableCell({
      width: { size: 50, type: WidthType.PERCENTAGE },
      borders: allNoBorder,
      margins: { top: 60, bottom: 60, left: 120, right: 120 },
      children: [
        new Paragraph({ children: [labelRun(label)] }),
        new Paragraph({ children: [valueRun(value || '—')] }),
      ],
    });
  }

  const metaRows: [string, string][] = [
    ['Enquiry No.',   enq.id],
    ['Date Received', fmtDate(enq.recv)],
    ['Customer',      enq.cust],
    ['Contact',       enq.contact || '—'],
    ['Email',         enq.email || '—'],
    ['Source',        enq.src || '—'],
    ['Assigned To',   enq.assigned || '—'],
    ['Priority',      enq.urg || '—'],
  ];
  if (enq.custEnqDocNo) metaRows.splice(2, 0, ['Cust. Enq. No.', enq.custEnqDocNo]);
  // Ensure even count
  if (metaRows.length % 2 !== 0) metaRows.push(['', '']);

  const metaTableRows: TableRow[] = [];
  for (let i = 0; i < metaRows.length; i += 2) {
    metaTableRows.push(new TableRow({
      children: [
        metaCell(metaRows[i][0], metaRows[i][1]),
        metaCell(metaRows[i + 1][0], metaRows[i + 1][1]),
      ],
    }));
  }

  // Items table header
  function th(text: string, w: number) {
    return new TableCell({
      width: { size: w, type: WidthType.DXA },
      shading: { type: ShadingType.SOLID, color: HEADBG },
      margins: { top: 80, bottom: 80, left: 120, right: 120 },
      children: [new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text, size: 16, bold: true, font: 'Calibri', color: '333333' })],
      })],
    });
  }

  function td(text: string, w: number, align: typeof AlignmentType[keyof typeof AlignmentType] = AlignmentType.LEFT) {
    return new TableCell({
      width: { size: w, type: WidthType.DXA },
      margins: { top: 60, bottom: 60, left: 120, right: 120 },
      children: [new Paragraph({
        alignment: align,
        children: [new TextRun({ text: String(text ?? '—'), size: 17, font: 'Calibri', color: DARK })],
      })],
    });
  }

  const DXA_PAGE = 9072; // usable width in DXA (~6.3")
  const colSeq = 500, colQty = 700, colUom = 700, colDrwg = 1200;
  const colDesc = Math.floor((DXA_PAGE - colSeq - colQty - colUom - colDrwg) * 0.55);
  const colMat  = DXA_PAGE - colSeq - colQty - colUom - colDrwg - colDesc;

  const itemRows = enq.items.map(i => new TableRow({
    children: [
      td(String(i.seq),      colSeq,  AlignmentType.CENTER),
      td(i.desc,             colDesc),
      td(i.mat || '—',      colMat),
      td(String(i.qty),      colQty,  AlignmentType.CENTER),
      td(i.uom || '—',      colUom,  AlignmentType.CENTER),
      td(i.drwg || '—',     colDrwg),
    ],
  }));

  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(0.7),
            bottom: convertInchesToTwip(0.7),
            left: convertInchesToTwip(0.8),
            right: convertInchesToTwip(0.8),
          },
        },
      },
      children: [
        // Company header
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [
            new TextRun({ text: CO_NAME, size: 28, bold: true, color: DARK, font: 'Calibri' }),
            new TextRun({ text: '   PURCHASE ENQUIRY', size: 18, color: GRAY, font: 'Calibri' }),
          ],
        }),

        // Horizontal rule via bottom border paragraph
        new Paragraph({
          border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'CCCCCC' } },
          children: [],
        }),

        new Paragraph({ children: [], spacing: { after: 120 } }),

        // Meta grid
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          borders: {
            top: noBorder, bottom: noBorder,
            left: noBorder, right: noBorder,
            insideHorizontal: noBorder, insideVertical: noBorder,
          },
          rows: metaTableRows,
        }),

        new Paragraph({ children: [], spacing: { after: 200 } }),

        // Notes
        ...(enq.notes ? [
          new Paragraph({
            children: [new TextRun({ text: 'NOTES', size: 14, bold: true, color: GRAY, font: 'Calibri' })],
          }),
          new Paragraph({
            children: [new TextRun({ text: enq.notes, size: 18, font: 'Calibri', color: DARK })],
            spacing: { after: 200 },
          }),
        ] : []),

        // Items heading
        new Paragraph({
          children: [new TextRun({ text: 'LINE ITEMS', size: 16, bold: true, color: RED, font: 'Calibri' })],
          spacing: { after: 100 },
        }),

        // Items table
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: [
                th('#',               colSeq),
                th('Description',     colDesc),
                th('Material / Grade', colMat),
                th('Qty',             colQty),
                th('UOM',             colUom),
                th('Dwg Ref',         colDrwg),
              ],
            }),
            ...itemRows,
          ],
        }),

        new Paragraph({ children: [], spacing: { after: 300 } }),

        // Footer
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated by ${CO_NAME} ERP · ${new Date().toLocaleString('en-IN')}`,
              size: 14, color: GRAY, italics: true, font: 'Calibri',
            }),
          ],
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${enq.id}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}
